const paragraphs = [
    "Explicar como se merecem quais e quão grandes foram, antes da perseguição de nosso tempo, a glória e a liberdade que gozou, entre todos os homens, gregos e bárbaros, a doutrina da piedade para com o Deus de todas as coisas e anunciada ao mundo por meio de Cristo, é empresa que nos transborda. Contudo, uma prova disso poderia ser a acolhida dos soberanos para com os nossos.",
    "Acima de todos que alguma vez foram celebrados como admiráveis e famosos por sua valentia, tanto entre os gregos quanto entre os bárbaros, esta foi a ocasião para destacar aos divinos e excelentes mártires Doroteu e os servidores imperiais que o acompanhavam. Embora seus amos os tivessem considerados dignos da mais alta honra e no trato não os deixavam abaixo de seus próprios filhos, eles julgavam, com toda a verdade.",
    "E para que, com o auxílio de Deus, possais seguir esse caminho, convivei em paz e chamai à concórdia os que estão em discórdia. Fugi da mentira e temei o perjúrio como a morte perpétua. Não digais falso testemunho e não furteis. E, sobretudo, como já dissemos, dai esmolas aos pobres de acordo com vossas possibilidades.",
    "Os muçulmanos golpearam os seus inimigos e atravessaram o rio Garonne, assolando o país e levando inúmeros cativos. Aquele exército passou por todos os lugares como uma tempestade devastadora. A prosperidade tornou esses guerreiros insaciáveis. Ao cruzarem o rio, Abderrahman arruinou o condado. O conde refugiou-se em sua fortaleza, mas os muçulmanos avançaram contra ele e, entrando à força no castelo, mataram o conde.",
    "Tudo isso nós ordenamos e cremos que nós falamos com o Dom dos Apóstolos, porque nós também acreditamos que nós temos o espírito de Cristo; e como nossos predecessores que creram no que declararam e definiram nos sínodos, nós também acreditamos e fazemos o que falamos e elaboramos alguns princípios que nos pareceram bons para serem seguidos conforme os princípios de nossos Pais...",
    "Mas dir-vos-eis da cona, qual é sua lei, como alguém que mal lhe fez e maior recebeu: se tudo diminui com o uso, com a cona aumenta. E aquele que não crer em minhas razões, que vá então vê-las perto do bosque, em um recanto para cada árvore que se poda, nascem duas ou três. Quando o bosque é podado, renasce mais espesso, e seu senhor não perde seus ganhos nem sustentos, mas lamenta o corte, se tem dano. Mau é lamentar o corte sem dano.",
    "O rei de Navarra foi conduzido a Paris por meu senhor Jean de Picquigny e alguns burgueses da cidade de Amiens e ali foi recebido com grande alegria. Todo tipo de gentes o acolheram com agrado, inclusive o duque da Normandia o festejou muito, coisa que lhe convinha, pois o preboste dos comerciantes e os de sua seita lhe obrigaram a fazê-lo. O duque fazia isso por dissimulação, ao agrado do preboste e de alguns de Paris.",
    "Estas gentes se mantinham unidas entre Paris e Noyon, e entre Paris e Soissons, e entre Soissons e Eu, em Vermandois, e por toda a terra de Coucy. Aí se encontravam os grandes violadores e criminosos, e saquearam entre as terras de Coucy, os bispados de Laon, Soissons e Noyon, mais de cem castelos e boas casas de cavaleiros e escudeiros, matando e roubando tudo o que encontravam.",
    "Nisto, todo tipo de gentes de armas saíram das filas e logo ganharam a praça, metendo-se entre os vilãos. Derrubaram-nos aos montões e os matavam como bestas, e os expulsaram fora da vila, pois entre eles não havia nenhuma ordem nem formação. Mataram tantos que se cansaram e caíram fartos, e os lançaram no rio Marne aos montões.",
    "Toda a Germânia está separada das Gálias, da Récia e da Panônia pelo Reno e Danúbio; da Sarmátia e da Dácia por alguns montes e por seus mútuos temores. O resto é circundado pelo Oceano, abrangendo golfos espaçosos e vastas ilhas, com habitantes e reis que a guerra nos fez descobrir recentemente. O Reno nasce de um despenhadeiro inacessível dos Alpes Récios, e depois de torcer um pouco para o poente desemboca no oceano setentrional.",
    "É sabido que os germanos não habitam em cidades cercadas nem admitem a construção de casas umas próximas das outras. Vivem divididos e separados, conforme lhes agrada a fonte, o prado, o bosque. Não edificam as aldeias como edificamos as nossas: os edifícios contíguos entre si. Circundam cada casa de certo espaço: ou por precaução contra incêndios ou para prevenir-se contra assaltos, ou por ignorância na arte de construir.",
    "Acaso não dizem os médicos do corpo que parte da medicina é precisamente determinar a ordem dos alimentos: qual deve ser ingerido antes, qual depois e o modo de os ingerir? Ora, mesmo sendo bons os alimentos que Deus criou, tu os tornas nocivos se não observas o modo e a ordem ao ingeri-los. Aplica, pois, aos saberes, o que dissemos dos alimentos.",
    "Que possa, então, a candura ser mostrada onde a deselegância de minhas palavras for insuficiente, e que a verdade desta história, que minha rude língua aventurou, como um tipo de arado,  para traçar nossos sulcos, não perca sua influência do que causa, nos ouvidos dos ouvintes. Porque é melhor beber de um único gole a verdade de um humilde receptáculo, do que o veneno misturado ao mel em uma taça de ouro.",
    "Muitos professores e escribas tentaram escrever isto, mas de algum modo ou outro abandonaram por causa da dificuldade, ou devido às mortes freqüentes, ou às recorrentes calamidades de guerra. Eu rezo para que todo leitor que deseja ler este Livro possa me perdoar, por haver tentado, como um tagarela tolo, ou como alguma fraca testemunha, a escrever estas coisas, depois que eles falharam.",
    "Todavia, Pepino foi educado pela ordem religiosa do pontífice romano, por ordem do majordomus, para ser rei, e governou os francos sozinho por quinze anos ou mais. Ele morreu de hidropisia, em Paris, ao fim da guerra da Aquitânia, travada durante nove anos sucessivos contra Guilherme, duque da Aquitânia, e deixou a sucessão a seus dois filhos, Carlos e Carlomano, pelos cuidados e pela graça de Deus."
];